### ISSUE TITLE
Fails to compile ovr_overlay_sys when installing from AUR

### ISSUE THREAD

**Issue by catgirlcataclysm** [galister/wlx-overlay-s#76]
I'm roughly 90% sure this is an issue with my system configs, but I cannot for the life of me figure out what exactly.
```

error: failed to run custom build command for "ovr_overlay_sys v0.0.0 (https://github.com/galister/ovr_overlay_oyasumi#bd03e5bf)"

Caused by:
  process didn't exit successfully: "/home/kaitlyn/.cache/paru/clone/wlx-overlay-s-git/src/wlx-overlay-s/target/release/build/ovr_overlay_sys-bc8fb4404462bb60/build-script-build" (exit status: 101)
  --- stderr
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:148:11: error: no member named 'fwide' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:149:11: error: no member named 'fwprintf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:150:11: error: no member named 'fwscanf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:160:11: error: no member named 'swprintf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:162:11: error: no member named 'swscanf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:164:11: error: no member named 'vfwprintf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:169:11: error: no member named 'vswprintf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:174:11: error: no member named 'vwprintf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:204:11: error: no member named 'wprintf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:205:11: error: no member named 'wscanf' in the global namespace
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/x86_64-pc-linux-gnu/bits/c++locale.h:52:23: error: use of undeclared identifier 'uselocale'
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/x86_64-pc-linux-gnu/bits/c++locale.h:62:11: error: unknown type name '__locale_t'
  thread 'main' panicked at /home/kaitlyn/.cargo/git/checkouts/ovr_overlay_oyasumi-1bb441442ac1b432/bd03e5b/sys/build.rs:11:10:
  Could not autogenerate bindings: ParseError(AutocxxCodegenError(Bindgen(ClangDiagnostic("/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:148:11: error: no member named 'fwide' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:149:11: error: no member named 'fwprintf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:150:11: error: no member named 'fwscanf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:160:11: error: no member named 'swprintf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:162:11: error: no member named 'swscanf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:164:11: error: no member named 'vfwprintf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:169:11: error: no member named 'vswprintf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:174:11: error: no member named 'vwprintf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:204:11: error: no member named 'wprintf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:205:11: error: no member named 'wscanf' in the global namespace\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/x86_64-pc-linux-gnu/bits/c++locale.h:52:23: error: use of undeclared identifier 'uselocale'\n/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/x86_64-pc-linux-gnu/bits/c++locale.h:62:11: error: unknown type name '__locale_t'\n"))))
  note: run with "RUST_BACKTRACE=1" environment variable to display a backtrace
  
```

  any help would be greatly appreciated :heart:

**Comment by galister** [comment]
are you on arch testing? i think this could be an issue with gcc somehow now working with the version of libstdc++ that you have

**Comment by catgirlcataclysm** [comment]
> are you on arch testing? i think this could be an issue with gcc somehow now working with the version of libstdc++ that you have

I am on arch, I can try spinning up a debian container or something and building in there

**Comment by catgirlcataclysm** [comment]
I tried compiling in a debian container, to no luck.


```
error: failed to run custom build command for `ovr_overlay_sys v0.0.0 (https://github.com/galister/ovr_overlay_oyasumi#bd03e5bf)`

Caused by:
  process didn't exit successfully: `/home/kaitlyn/software/wlx-overlay-s/target/release/build/ovr_overlay_sys-ac1ed77ef297dcb2/build-script-build` (exit status: 101)
  --- stderr
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:148:11: error: no member named 'fwide' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:149:11: error: no member named 'fwprintf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:150:11: error: no member named 'fwscanf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:160:11: error: no member named 'swprintf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:162:11: error: no member named 'swscanf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:164:11: error: no member named 'vfwprintf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:169:11: error: no member named 'vswprintf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:174:11: error: no member named 'vwprintf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:204:11: error: no member named 'wprintf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:205:11: error: no member named 'wscanf' in the global namespace
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12/bits/c++locale.h:52:23: error: use of undeclared identifier 'uselocale'
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12/bits/c++locale.h:62:11: error: unknown type name '__locale_t'
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4155:51: error: no member named 'vswprintf' in namespace 'std'
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4160:51: error: no member named 'vswprintf' in namespace 'std'
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4166:51: error: no member named 'vswprintf' in namespace 'std'
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4171:51: error: no member named 'vswprintf' in namespace 'std'
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4177:51: error: no member named 'vswprintf' in namespace 'std'
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4183:51: error: no member named 'vswprintf' in namespace 'std'
  /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4192:51: error: no member named 'vswprintf' in namespace 'std'
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  thread 'main' panicked at /home/kaitlyn/.cargo/git/checkouts/ovr_overlay_oyasumi-1bb441442ac1b432/bd03e5b/sys/build.rs:11:10:
  Could not autogenerate bindings: ParseError(AutocxxCodegenError(Bindgen(ClangDiagnostic("/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:148:11: error: no member named 'fwide' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:149:11: error: no member named 'fwprintf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:150:11: error: no member named 'fwscanf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:160:11: error: no member named 'swprintf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:162:11: error: no member named 'swscanf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:164:11: error: no member named 'vfwprintf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:169:11: error: no member named 'vswprintf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:174:11: error: no member named 'vwprintf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:204:11: error: no member named 'wprintf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/cwchar:205:11: error: no member named 'wscanf' in the global namespace\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12/bits/c++locale.h:52:23: error: use of undeclared identifier 'uselocale'\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12/bits/c++locale.h:62:11: error: unknown type name '__locale_t'\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4155:51: error: no member named 'vswprintf' in namespace 'std'\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4160:51: error: no member named 'vswprintf' in namespace 'std'\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4166:51: error: no member named 'vswprintf' in namespace 'std'\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4171:51: error: no member named 'vswprintf' in namespace 'std'\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4177:51: error: no member named 'vswprintf' in namespace 'std'\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4183:51: error: no member named 'vswprintf' in namespace 'std'\n/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:4192:51: error: no member named 'vswprintf' in namespace 'std'\nfatal error: too many errors emitted, stopping now [-ferror-limit=]\n"))))
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by galister** [comment]
in that case, you might as well grab the appimage, because that's how an appimage is made, too.

**Comment by catgirlcataclysm** [comment]
that's a good point, thanks for the help though. :+1:
